### ISSUE TITLE
Semantic bug: different exception thrown

### ISSUE THREAD

**Issue by esbena** [Samsung/jalangi2#18]
A browserified browserify behaves differently when run with Jalangi:

Original behaviour:
```
TypeError: Object #<Object> has no method 'readFileSync'
```
Jalangi behaviour:
```
TypeError: Function.prototype.apply was called on undefined, which is a undefined and not a function
```

To reproduce:
In jalangi2 directory:

```bash
$ npm install -g browserify
$ mkdir bug
$ cd bug
$ mkdir node_modules
$ npm install browserify
$ echo 'require("browserify");' >> main.js
$ node main.js 
$ browserify main.js -o bundle.js
$ node bundle.js 

/Users/e.andreasen/workspace/jalangi2/bug/bundle.js:845
var defaultPrelude = fs.readFileSync(defaultPreludePath, 'utf8');
                        ^
TypeError: Object #<Object> has no method 'readFileSync'
    at Object.<anonymous> (/Users/e.andreasen/workspace/jalangi2/bug/bundle.js:845:25)
    at Object.JSONStream (/Users/e.andreasen/workspace/jalangi2/bug/bundle.js:955:4)
    at s (/Users/e.andreasen/workspace/jalangi2/bug/bundle.js:1:316)
    at /Users/e.andreasen/workspace/jalangi2/bug/bundle.js:1:367
    at Object.<anonymous> (/Users/e.andreasen/workspace/jalangi2/bug/bundle.js:8:13)
    at Object../lib/builtins.js (/Users/e.andreasen/workspace/jalangi2/bug/bundle.js:791:4)
    at s (/Users/e.andreasen/workspace/jalangi2/bug/bundle.js:1:316)
    at /Users/e.andreasen/workspace/jalangi2/bug/bundle.js:1:367
    at Object.browserify (/Users/e.andreasen/workspace/jalangi2/bug/bundle.js:2:1)
    at s (/Users/e.andreasen/workspace/jalangi2/bug/bundle.js:1:316)
$ cd ..
$ node src/js/commands/jalangi.js --inlineIID --inlineSource --analysis src/js/sample_analyses/ChainedAnalyses.js --analysis src/js/sample_analyses/dlint/Utils.js --analysis src/js/sample_analyses/dlint/CheckNaN.js bug/bundle.js 

/Users/e.andreasen/workspace/jalangi2/src/js/runtime/analysis.js:440
            throw tmp;
                  ^
TypeError: Function.prototype.apply was called on undefined, which is a undefined and not a function
    at callFun (/Users/e.andreasen/workspace/jalangi2/src/js/runtime/analysis.js:145:51)
    at invokeFun (/Users/e.andreasen/workspace/jalangi2/src/js/runtime/analysis.js:166:22)
    at /Users/e.andreasen/workspace/jalangi2/src/js/runtime/analysis.js:189:41
    at Object.<anonymous> (/Users/e.andreasen/workspace/jalangi2/bug/bundle.js:2278:195)
    at callFun (/Users/e.andreasen/workspace/jalangi2/src/js/runtime/analysis.js:145:51)
    at invokeFun (/Users/e.andreasen/workspace/jalangi2/src/js/runtime/analysis.js:166:22)
    at /Users/e.andreasen/workspace/jalangi2/src/js/runtime/analysis.js:189:41
    at Object.J$.X1.J$.F.J$.T.J$.T.J$.T.JSONStream (/Users/e.andreasen/workspace/jalangi2/bug/bundle.js:2516:73)
    at callFun (/Users/e.andreasen/workspace/jalangi2/src/js/runtime/analysis.js:145:51)
    at invokeFun (/Users/e.andreasen/workspace/jalangi2/src/js/runtime/analysis.js:166:22)
```

**Comment by esbena** [comment]
Koushik: works as inteded.
The concrete exception and call stack is not maintained by Jalangi. *Some* exception occur at the right iid, that is the important thing.

In this case, the `o.readFileSync` property is not present (orig. exception), but Jalangi invokes that undefined value with `Function.prototype.apply`, leading to a slightly different error message.
