### ISSUE TITLE
Crash: Circular JSON on 3d-raytrace.js

### ISSUE THREAD

**Issue by magnus-madsen** [Samsung/jalangi2#31]
The newest version of Jalangi crashes on 3d-raytrace.js with

sandbox.Config.ENABLE_SAMPLING = true;

and exception:

/Users/m.madsen/Arov/lib/jalangi2/src/js/instrument/esnstrument.js:1177
        return JSON.parse(JSON.stringify(src), JSONParseHandler);
                               ^
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at clone (/Users/m.madsen/Arov/lib/jalangi2/src/js/instrument/esnstrument.js:1177:32)
    at Object.visitorCloneBodyPre.FunctionDeclaration (/Users/m.madsen/Arov/lib/jalangi2/src/js/instrument/esnstrument.js:1251:29)
    at transformAst (/Users/m.madsen/Arov/lib/jalangi2/src/js/instrument/astUtil.js:148:36)
    at transformAst (/Users/m.madsen/Arov/lib/jalangi2/src/js/instrument/astUtil.js:141:39)
    at Object.transformAst (/Users/m.madsen/Arov/lib/jalangi2/src/js/instrument/astUtil.js:141:39)
    at transformString (/Users/m.madsen/Arov/lib/jalangi2/src/js/instrument/esnstrument.js:1759:30)
    at Object.instrumentCode (/Users/m.madsen/Arov/lib/jalangi2/src/js/instrument/esnstrument.js:1819:26)
    at Object.Module._extensions..js (/Users/m.madsen/Arov/lib/jalangi2/src/js/commands/jalangi.js:77:30)
    at Module.load (module.js:355:32)

**Comment by ksen007** [comment]
Hi Magnus,  please describe the exact command your are running.

**Comment by magnus-madsen** [comment]
/usr/local/bin/node lib/jalangi2/src/js/commands/jalangi.js --analysis src/js/Empty.js lib/jalangi2/tests/sunspider1/3d-raytrace.js

Here Empty.js is an empty analysis (i.e. it implements none of the callback functions).

**Comment by magnus-madsen** [comment]
Specific steps to reproduce:
1. git clone https://github.com/Samsung/jalangi2.git
2. cd jalangi2.
3. Create Empty.js with body:
  (function (sandbox) {
  })(J$);
4. Edit src/js/Config.js to enable sampling.
4. Run node src/js/commands/jalangi.js --analysis Empty.js tests/sunspider1/3d-raytrace.js
