### ISSUE TITLE
Disabling INSTR_TRY_CATCH_ARGUMENTS throws IllegalStateException

### ISSUE THREAD

**Issue by magnus-madsen** [Samsung/jalangi2#36]
Steps to reproduce:
1. Clean Jalangi2 install.
2. Edit Config.js to enable INSTR_TRY_CATCH_ARGUMENTS and always return false.
3. Run node jalangi2/src/js/commands/instrument.js --outputDir foo jalangi2/tests/octane/box2d.js

/Users/m.madsen/tmp/jalangi2/src/js/commands/instrument.js:322
                    throw e;
                          ^
Error: IllegalStateException
    at getFnIdFromAst (/Users/m.madsen/tmp/jalangi2/src/js/instrument/esnstrument.js:531:19)
    at wrapLiteral (/Users/m.madsen/tmp/jalangi2/src/js/instrument/esnstrument.js:554:37)
    at Object.visitorRRPost.FunctionExpression (/Users/m.madsen/tmp/jalangi2/src/js/instrument/esnstrument.js:1386:24)
    at transformAst (/Users/m.madsen/tmp/jalangi2/src/js/instrument/astUtil.js:148:36)
    at transformAst (/Users/m.madsen/tmp/jalangi2/src/js/instrument/astUtil.js:141:39)
    at transformAst (/Users/m.madsen/tmp/jalangi2/src/js/instrument/astUtil.js:141:39)
    at transformAst (/Users/m.madsen/tmp/jalangi2/src/js/instrument/astUtil.js:141:39)
    at transformAst (/Users/m.madsen/tmp/jalangi2/src/js/instrument/astUtil.js:141:39)
    at transformAst (/Users/m.madsen/tmp/jalangi2/src/js/instrument/astUtil.js:141:39)
    at transformAst (/Users/m.madsen/tmp/jalangi2/src/js/instrument/astUtil.js:141:39)

**Comment by ksen007** [comment]
This is an untested feature and I am not sure how this can be implemented correctly.
